apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proj
  template:
    metadata:
      name: project-webserver
      labels:
        app: proj
    spec:
      containers:
      - name: pj-websrv-ctn
        image: 814667018602.dkr.ecr.ap-northeast-1.amazonaws.com/project/app:1.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: DATE
            value: 'DATE_STRING'
#        resources:
#          limits:
#            cpu: 500m
#          requests:
#            cpu: 200m